new branch develop
kuznetsovvvv/service pull request #1
Opened 2024-11-08 16:23 UTC by kuznetsovvvv

2024-11-09 09:26 UTC, zinstack625 reviewed
Очень много времени потрачено на работу с потоками ввода-вывода, жалко, можно было бы просто в бдшку заслать захардкоженные константы в качестве эксперимента

Работа с самой БД в целом корректная. Момент что не понравился пометил

Структура кода оставляет очень многого желать, но пока это не завязано на остальных системах, не поздно поменять:
- [ ] Точно надо сущности БД выделить в классы. Делать всё на бесструктурных локальных переменных нельзя
- [ ] Заполнение этих структур (и сейчас локальных переменных тоже) стоит отделить функционально и желательно семантически от работы с БД. То есть функции (или методы) для работы с БД должны принимать готовые структуры и менять их содержимое только в техническом случае, а желательно и вовсе не менять (`throw InvalidArguments` и всё)
- [ ] Работу с БД стоит организовать в класс, который будет инкапсулировать всё что связано с БД непосредственно и только предоставлять интерфейс по абстрактным действиям сохранения, получения, удаления и возможно модификации сущностей в персистентном хранилище
- [ ] Сам эксперимент выносить не надо, но стоит его оформить как юнит-тесты, например на основе GTest

2024-11-09 09:26 UTC, zinstack625 commented on functions.h
> +        }
Проверки такого типа лучше делать как
```sql
SELECT EXISTS(SELECT * FROM products WHERE product_id = $1)
```
Так и БДшка быстрее отработает, и булевое значение обрабатывать проще

2024-11-11 19:00 UTC, zinstack625 requested changes
На всякий продублирую сюда:

Некоторые методы в БДшке до сих пор стучатся в `cin`, `cout`, такого быть не должно. Для логов в целом можно, но meh, лучше использовать либы с логгерами, например Boost Log

Функции типа `update_.*` должны принимать объекты, и, на основании их полей (например `id`), обновлять записи в БД, предварительно удостоверившись что в базе оно ничего не поломает. Никаких вводов со стандартных потоков

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +        pqxx::result result = check.exec_params("SELECT 1 FROM couriers WHERE courier_id=$1", obj.get_courier_id());
`SELECT EXISTS`

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +        }
Интересно какой некритичный catch тут можно поймать?

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +       if (!result.empty() && result[0][0].as<bool>()) {
> `!result.empty()`

`SELECT EXISTS` всегда что-то возвращает. Если это не так, стоит поменять лампочку

Применимо везде где это есть

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +            delete_prod.exec_params("DELETE FROM products WHERE product_id=$1", obj.get_product_id());
Договорились же ничего из базы не удалять, а просто помечать как неактивное...

Что с заказами завершёнными будет если это удалить?

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +        }
Думаю можно и без этой проверки, если внимательно посмотреть на то что возвращает результат следующего запроса. Применимо везде

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +void check_product(db::product& obj){
Какова цель этого метода с учётом что он ничего не возвращает?

`check_order` и `check_user` аналогично

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +  std::string time=asctime (timeinfo);
Может быть `std::chrono`?

2024-11-11 19:00 UTC, zinstack625 commented on functions.h
> +          "INSERT INTO orders (order_id, creation_time, time, delivery_address, status) VALUES (DEFAULT, $1, $2, $3, $4)",
А ещё лучше прямо тут в запросе. На выбор: https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT

К сожалению саму схему базы в действительности я не вижу, поэтому что именно использовать не подскажу

2024-11-13 21:17 UTC, zinstack625 requested changes
Запросы норм. Кажется запланированный функционал слоя БД соответствует плану.

После, или в процессе исправления замечаний, можно приступить к реализации апишки. Так как апишка одна и особо бизнес-логики в сервисе не будет, можно скипнуть этап с отдельной реализацией доступного пользователю функционала и сделать это частью непосредственно апи (или при необходимости в процессе выносить наружу).

Прошу обратить внимание что апишка становится перечнем доступного пользователю функционала. Она не диктует (и желательно не рекомендует) __как__ пользователь совершает действия, а __является__ этими действиями пользователя, то есть удобство её использования нужно оценивать с точки зрения программиста, а не с точки зрения конечного пользователя. При её построении нужно учитывать что пользователь может передать значения не соответствующие ожидаемым, неполные, излишне полные и лишние -- это всё необходимо корректно обрабатывать. Апишка одновременно и предоставляет пользователю доступный функционал, и ограничивает его в нём. На практике это может сказываться как, например, как полное отграничение пользователя апишки от некоторых колонок БД (например, айдишников), но вряд-ли это тут понадобится

2024-11-13 21:17 UTC, zinstack625 commented on functions.h
> +    try {
Технически обработка ошибок здесь возможна, но обрабатывать все ошибки сразу -- идея не очень. Я обычно придерживаюсь идее что пока ошибки нет (на практике, в теории не годится), обрабатывать их не надо. Когда ошибка есть, необходимо удостовериться, что её обработка не влияет на ожидаемый функционал и на сложности её обработки, как вычислительную, так и когнитивную

Применимо везде

 Рекомендую пробрасывать исключение дальше по стеку вызовов

2024-11-13 21:17 UTC, zinstack625 commented on functions.h
> +  }
В функциях добавления сущностей в базу думаю будет логично возвращать сгенерированные БД поля, в частности айдишники. Самое логичное думаю будет модифицировать передаваемые аргументом объекты, но подход с возвратом значения функцией тоже имеет место быть

2024-11-13 21:17 UTC, zinstack625 commented on functions.h
> +  void update_courier(db::courier &obj) {
В функциях `update_*` тоже было бы полезно что-то возвращать. Ситуацию с некорректным входом в виде несуществующего айдишника было бы полезно отследить извне. Можно даже бросить новое исключение

2024-11-13 21:17 UTC, zinstack625 commented on functions.h
> +  void get_info_courier(db::courier &obj) {
Очень странно что функции `get` ничего не возвращают. Полагаю аргумент можно оставить как источник фильтров для запроса, и даже пометить как `const`, а вот полученные значения из `result` надо бы как-то отдать наружу

2024-11-22 07:31 UTC, zinstack625 requested changes
То что есть выглядит почти норм. Оставил как требование к редактированию потому что кажется после правок поменяется функционал слегка (сервак будет выбрасывать Internal Server Error чуть реже)

Ещё пока не оценивал полноту апишки, постараюсь чутка позже это сделать

2024-11-22 07:31 UTC, zinstack625 commented on main.cc
> +          }
Уже была фильтрация по методу запроса. Это мёртвый код

2024-11-22 07:31 UTC, zinstack625 commented on main.cc
> +              201,
Magic number. Сильно сомневаюсь что через неделю будет идеальное соображение что значит `201`

```suggestion
              crow::status::CREATED,
```

Список методов есть тут: http://crowcpp.org/master/reference/namespacecrow.html#aa3ae5c0994dff8425d7515e2806180d2

2024-11-22 07:31 UTC, zinstack625 commented on main.cc
> +        try {
try на всю функу это не хорошо. Лучше обрабатывать конкретные места. Опишу в других комментах

2024-11-22 07:31 UTC, zinstack625 commented on main.cc
> +          string active = json["active"].s();
Можно вместо предварительной проверки на наличие полей обработать исключение. Индексация в несуществующий ключ и попытка некорректной эллизии типа в поле бросают `std::runtime_error`. Кажется разбираться по какой именно причине оно исключение вываливает нет смысла, просто вернуть Bad Request

2024-11-22 07:31 UTC, zinstack625 commented on main.cc
> +          postgres.add_courier(courier1);
БДшка вообще говоря тоже должна уметь вываливать ошибки, но ладно. Вот в этом случае Internal Server Error оправдан

2024-11-22 07:31 UTC, zinstack625 commented on main.cc
> +          postgres.update_courier(courier1);
Делали же кажется на опционалах специально для этого... Или нет?

2024-11-23 09:42 UTC, kuznetsovvvv commented on main.cc
> +          postgres.update_courier(courier1);
?

2024-12-07 20:36 UTC, merged